language: generic  # Main thing we need from generic over minimal is the JVM

cache:
  directories:
    - $HOME/.m2
    - .cpcache # tools.deps classpath cache
    - ~/.cache
    - ~/.gitlibs


install:
  - sudo apt-get install -y rlwrap
  - "travis/install_clojure.sh"
  - "sudo travis/configure_private_maven.sh"

script:
  - ./bin/kaocha --reporter documentation --fail-fast

after_success:
  - lein uberjar
  - mkdir "target/table2qb-$TRAVIS_BRANCH"
  - cp target/table2qb.jar "target/table2qb-$TRAVIS_BRANCH"
  - cp travis/table2qb.sh "target/table2qb-$TRAVIS_BRANCH/table2qb"
  - zip -r "target/table2qb-$TRAVIS_BRANCH.zip" "target/table2qb-$TRAVIS_BRANCH"

deploy:
  - provider: releases
    api_key: "$RELEASE_OAUTH_TOKEN"
    file: "target/table2qb-$TRAVIS_BRANCH.zip"
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_TAG =~ ^[0-9]+\.[0-9]+\.[0-9]+$
  - provider: script
    script: lein deploy
