PREFIX ui: <http://www.w3.org/ns/ui#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?scheme ?code ?description WHERE {
  ?code
    skos:inScheme ?scheme;
    rdfs:comment ?description;
    .
}