PREFIX ui: <https://www.w3.org/ns/ui#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>

SELECT ?scheme ?code ?priority WHERE {
  ?code
    skos:inScheme ?scheme;
    ui:sortPriority ?priority;
    .
}